services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --host=postgres --username=postgres" ]
      interval: 60s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 60s
      timeout: 5s
      retries: 5

  note-keeper:
    image: note-keeper:latest
    build:
      context: .
      dockerfile: ./src/NoteKeeper.Api/Dockerfile

    environment:
      VaultOptions__ServerUri: "${VAULT_SERVER}"
      VaultOptions__Token: "${VAULT_TOKEN}"
      VaultOptions__MountPoint: "${VAULT_MOUNT_POINT}"
      VaultOptions__SecretsPath: "${VAULT_SECRETS_PATH}"
      USE_VAULT: "${USE_VAULT}"

    ports:
      - "${APPLICATION_HTTP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
    driver: local
