//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteKeeper.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NoteKeeper.Shared.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UsernameValidation {
            get {
                return ResourceManager.GetString("UsernameValidation", resourceCulture);
            }
        }
        
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        public static string AlreadySignedIn {
            get {
                return ResourceManager.GetString("AlreadySignedIn", resourceCulture);
            }
        }
        
        public static string PropertyNotUniqueTemplate {
            get {
                return ResourceManager.GetString("PropertyNotUniqueTemplate", resourceCulture);
            }
        }
        
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        public static string NoTokensFound {
            get {
                return ResourceManager.GetString("NoTokensFound", resourceCulture);
            }
        }
        
        public static string EntityNotFoundByUuidTemplate {
            get {
                return ResourceManager.GetString("EntityNotFoundByUuidTemplate", resourceCulture);
            }
        }
        
        public static string OAuthTemplate {
            get {
                return ResourceManager.GetString("OAuthTemplate", resourceCulture);
            }
        }
        
        public static string GoogleTokenRevocation {
            get {
                return ResourceManager.GetString("GoogleTokenRevocation", resourceCulture);
            }
        }
        
        public static string GoogleSignin {
            get {
                return ResourceManager.GetString("GoogleSignin", resourceCulture);
            }
        }
        
        public static string GoogleSignup {
            get {
                return ResourceManager.GetString("GoogleSignup", resourceCulture);
            }
        }
        
        public static string GoogleOidc {
            get {
                return ResourceManager.GetString("GoogleOidc", resourceCulture);
            }
        }
        
        public static string GoogleRefreshToken {
            get {
                return ResourceManager.GetString("GoogleRefreshToken", resourceCulture);
            }
        }
    }
}
