//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteKeeper.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NoteKeeper.Shared.Resources.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string TokenRefresh {
            get {
                return ResourceManager.GetString("TokenRefresh", resourceCulture);
            }
        }
        
        public static string UpdateTemplate {
            get {
                return ResourceManager.GetString("UpdateTemplate", resourceCulture);
            }
        }
        
        public static string DeleteTemplate {
            get {
                return ResourceManager.GetString("DeleteTemplate", resourceCulture);
            }
        }
        
        public static string GoogleTokenRevocation {
            get {
                return ResourceManager.GetString("GoogleTokenRevocation", resourceCulture);
            }
        }
        
        public static string GoogleSigninTemplate {
            get {
                return ResourceManager.GetString("GoogleSigninTemplate", resourceCulture);
            }
        }
        
        public static string GoogleSignupTemplate {
            get {
                return ResourceManager.GetString("GoogleSignupTemplate", resourceCulture);
            }
        }
        
        public static string GoogleRefreshToken {
            get {
                return ResourceManager.GetString("GoogleRefreshToken", resourceCulture);
            }
        }
        
        public static string OAuthSuccessTemplate {
            get {
                return ResourceManager.GetString("OAuthSuccessTemplate", resourceCulture);
            }
        }
    }
}
