// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteKeeper.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoteKeeper.DataAccess.Migrations
{
    [DbContext(typeof(UnitOfWork))]
    [Migration("20250608202235_ConvertToCleanArchitecture")]
    partial class ConvertToCleanArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("DomainEntitySequence");

            modelBuilder.Entity("NoteKeeper.Domain.Entities.DomainEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"DomainEntitySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("NoteKeeper.Infrastructure.ExternalServices.Google.Data.GoogleToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("Varchar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdToken")
                        .HasMaxLength(5000)
                        .HasColumnType("Varchar");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("Varchar");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("Varchar");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("GoogleTokens");
                });

            modelBuilder.Entity("NoteKeeper.Infrastructure.ExternalServices.Notion.Data.NotionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("Varchar");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(250)
                        .HasColumnType("Varchar");

                    b.Property<string>("BotId")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("NotionEmail")
                        .HasMaxLength(320)
                        .HasColumnType("Varchar");

                    b.Property<string>("NotionId")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkspaceIconUrl")
                        .HasMaxLength(250)
                        .HasColumnType("Varchar");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("WorkspaceName")
                        .HasMaxLength(150)
                        .HasColumnType("Varchar");

                    b.HasKey("Id");

                    b.ToTable("NotionTokens");
                });

            modelBuilder.Entity("NoteKeeper.Domain.Entities.ExternalProviderAccount", b =>
                {
                    b.HasBaseType("NoteKeeper.Domain.Entities.DomainEntity");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("ProviderType")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalProviderAccounts");
                });

            modelBuilder.Entity("NoteKeeper.Domain.Entities.Note", b =>
                {
                    b.HasBaseType("NoteKeeper.Domain.Entities.DomainEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("Varchar");

                    b.Property<byte>("Origin")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteKeeper.Domain.Entities.User", b =>
                {
                    b.HasBaseType("NoteKeeper.Domain.Entities.DomainEntity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("Varchar");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("Varchar");

                    b.Property<byte>("RegistrationType")
                        .HasColumnType("smallint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("Varchar");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NoteKeeper.Domain.Entities.ExternalProviderAccount", b =>
                {
                    b.HasOne("NoteKeeper.Domain.Entities.User", "User")
                        .WithMany("ExternalProviderAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteKeeper.Domain.Entities.Note", b =>
                {
                    b.HasOne("NoteKeeper.Domain.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteKeeper.Domain.Entities.User", b =>
                {
                    b.Navigation("ExternalProviderAccounts");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
