// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace NoteKeeper.DataAccess.Migrations
{
    [DbContext(typeof(NoteKeeperDbContext))]
    [Migration("20241011184534_AddTokenStateInformation")]
    partial class AddTokenStateInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.GoogleToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdToken")
                        .HasMaxLength(5000)
                        .HasColumnType("VarChar");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VarChar");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VarChar");

                    b.Property<long>("TokenStateId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoogleTokens");
                });

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.TokenStateInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TokenStateInformation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1060),
                            Description = "Neither access token nor refresh token has been revoked.",
                            Title = "Active",
                            UpdatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1060),
                            Uuid = new Guid("a0cf4d5f-ed6b-4de2-bfcb-01e14ddbd825")
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1110),
                            Description = "Both tokens have been revoked.",
                            Title = "Deleted",
                            UpdatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1110),
                            Uuid = new Guid("7e004b48-e8e8-498d-886f-4b12cb3e0134")
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1120),
                            Description = "Access token has been revoked.",
                            Title = "Access Token Revoked",
                            UpdatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1120),
                            Uuid = new Guid("0d448d91-52c6-49e1-853f-2618ae0dca7c")
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1120),
                            Description = "Refresh token has been revoked.",
                            Title = "Refresh Token Revoked",
                            UpdatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1120),
                            Uuid = new Guid("3e0d5148-919f-4029-a179-c2c592c88894")
                        });
                });

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("VarChar");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("VarChar");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1220),
                            Email = "sepfrd@outlook.com",
                            PasswordHash = "$2a$12$SvvxrIjm9.UKcP/Qjl.c6efFh/RgIO5XRqYBP/QO01/AWsmFUlP4C",
                            UpdatedAt = new DateTime(2024, 10, 11, 18, 45, 33, 577, DateTimeKind.Utc).AddTicks(1220),
                            Username = "sepehr_frd",
                            Uuid = new Guid("f0a8a301-7075-44f9-8491-b036934d23f7")
                        });
                });

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.GoogleToken", b =>
                {
                    b.HasOne("NoteKeeper.DataAccess.Entities.User", "User")
                        .WithOne("GoogleToken")
                        .HasForeignKey("NoteKeeper.DataAccess.Entities.GoogleToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.Note", b =>
                {
                    b.HasOne("NoteKeeper.DataAccess.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteKeeper.DataAccess.Entities.User", b =>
                {
                    b.Navigation("GoogleToken");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
